version: '2'

services:
  mallory:
      build: ./mallory
      image: mallory
      container_name: mallory
      tty: true
      restart: always
      cap_add:
        - NET_ADMIN
      volumes:
          - ./mallory:/shared
      networks:
        internal:
          ipv4_address: 10.0.0.2

  alice:
    build: ./alice
    image: alice
    container_name: alice
    tty: true
    networks:
      internal:
        ipv4_address: 10.0.0.3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
