<div class="jumbotron">
  <div id="post-container" class="form-group">
  <div class="form-group has-success has-feedback">
    <label class="control-label" for="post">Your new post</label>
    <textarea type="text" class="form-control" id="post-form" placeholder="Your post"></textarea>
    <!--span class="glyphicon glyphicon-ok form-control-feedback"></span-->
  </div>
  <button id="post-button" type="submit" class="btn btn-lg btn-primary">Post</button>
  </div>
</div>