<li>
<div id="signin-container" class="form-inline form-group">
  <form class="form-group" id="signin-form" action='signin.php' method='post'>
    <input type="email" class="form-control" id="email" placeholder="email" name="email">
    <input type="password" class="form-control" id="password" placeholder="Password" name="password">
  </form>
  <button id="signin-button" type="submit" class="btn btn-primary">Sign in</button>
  <button id="signup-button" type="button" class="btn btn-link">Sign up</button>
</div>
</li>