version: '2'

services:
  vulnapp:
    build: ./vulnapp
    image: vulnapp
    container_name: vulnapp
    ports:
      - "8080:80"
    networks:
      channel:
        ipv4_address: 10.0.0.2

  alice:
    build: ./alice
    image: alice
    container_name: alice
    tty: true
    networks:
      channel:
        ipv4_address: 10.0.0.3

  mallory:
      build: ./mallory
      image: mallory
      container_name: mallory
      tty: true
      volumes:
          - ./mallory:/shared
      networks:
        channel:
          ipv4_address: 10.0.0.4

networks:
  channel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24