version: '2'

services:
  alice:
    build: ./alice
    image: alice
    container_name: alice
    networks:
      legitimate:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN

  mallory:
      build: ./mallory
      image: mallory
      container_name: mallory
      tty: true
      restart: always
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      volumes:
          - ./mallory:/shared
      networks:
        legitimate:
          ipv4_address: 10.0.0.3
        malicious:
          ipv4_address: 10.0.1.3
  
  wireshark:
    build: ./wireshark
    image: wireshark
    container_name: wireshark
    tty: true
    network_mode: service:mallory

networks:
  legitimate:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  malicious:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
